config/routes.rb
Rails.application.routes.draw do

  devise_for :user

  resources :user, only: [:index, :show]

  resources :registered_applications, except: [:index]

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#options', via: [:options]
    resources :events, only: [:create]
  end

root :to => "welcome#index"

end

app/models/application.rb
class Application < ActiveRecord::Base

  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :registered_application
  
  validates :registered_application_id, presence: true

end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base

  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  has_many :registered_applications, dependent: :destroy

  def admin?
    role == "admin"
  end

  def member?
    role == "member"
  end

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  #before_action :authenticated?
  
  before_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin']  = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def options
    head :no_content
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if RegisteredApplication.all.include?(registered_application)
      @event = Event.new(event_params)
      @event.registered_application = registered_application
      
      if @event.save!
        render json: @event, status: :created
      else
        render @event.errors, status: :unprocessable_entity
      end
      
    else
      render json: "Unregistered application", status: :unprocessable_entity   
    end
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token


  private

  def current_user
    @user 
  end

  def authenticated?
    authenticate_or_request_with_http_basic {|name, password|
      @user = User.find_by( name: name, password: password)
      @user.present?
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: "Unauthorized."
  end

  
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def new
    @registered_application = RegisteredApplication.new
    @user = current_user
    authorize @registered_application
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application
    @events = @registered_application.events.group_by(&:name)
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
    @user = current_user
    authorize @registered_application
  end

  def create
    @registered_application = current_user.registered_applications.build(registered_application_params)
    authorize @registered_application
    if @registered_application.save
      redirect_to registered_application_path(@registered_application), notice: "Application was saved successfully."
    else
      flash[:error] = "There was an error creating the Application. Please try again."
      render :new
    end
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application
    if @registered_application.update_attributes(registered_application_params)
      redirect_to registered_application_path
    else
      flash[:error] = "There was an error updating the application. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    @user = @registered_application.user
    authorize @registered_application
    
    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" was deleted."
      redirect_to user_path(@user)
    else
      flash[:error] = "There was an error deleting the application. Please try again."
      render :show
    end
  end

private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
  
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end

   
end

app/helpers/registered_application_helper.rb
module RegisteredApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/_form.html.erb
<%= form_for [@application] do |f| %>
   
  <% if application.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(application.errors.count, "error") %>.</h4>
      <ul>
        <% application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= form_group_tag(application.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  <% end %>

  <%= form_group_tag(application.errors[:url]) do %>
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
  <% end %>
  
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
 
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocmetrics", root_path %></li>
      <li><%#= link_to "Applications", user_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>

          Hello <%= (current_user.name || current_user.email) %>!

          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-log-out"></span>
          <% end %>


        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>


       <%= link_to "Users", user_index_path %>
       <%#= link_to "Applications", applications_path %>



    <%= yield %>
  </div>
</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for [@registered_application] do |f| %>
   
  <% if registered_application.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(registered_application.errors.count, "error") %>.</h4>
      <ul>
        <% registered_application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= form_group_tag(registered_application.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  <% end %>

  <%= form_group_tag(registered_application.errors[:url]) do %>
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
  <% end %>
  
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
 
 <% end %>

app/views/registered_applications/_registered_application.html.erb
<p><%= link_to registered_application.name, registered_application %></p>
<p><%= registered_application.url %></p>

app/views/registered_applications/edit.html.erb
<h1>Edit Application</h1>

<div class="row">
  <div class="col-md-8">
  
    <%= render partial: 'form', locals: { registered_application: @registered_application } %>

  </div>
</div>

app/views/registered_applications/index.html.erb
<h1>Applications</h1>


<div class="row">
  <div class="col-md-8">
  <%= render @registered_applications %>
<%= will_paginate @registered_applications %>
  </div>
  <div class="col-md-4">
    <%# if policy(registered_application.new).create? %>
      <%= link_to "New application", new_user_registered_application_path, class: 'btn btn-success' %>
    <%# end %>
  </div>


</div>

app/views/registered_applications/new.html.erb
<h1>New Application</h1>

<div class="row">
  <div class="col-md-8">

    <%= render partial: 'form', locals: { registered_application: @registered_application, user: @user } %>

  </div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>

<p><%= @registered_application.url %></p>
<p>User: <%= @registered_application.user.id %></p>
<p>User: <%= current_user.id %></p>


<%# @events.each_with_index do |event, i| %>
<!-- <p><%#= i + 1 %>. <%#= event[0] %> - <%#= event[1].count - 1 %></p> -->
<%# end %>

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= pie_chart @registered_application.events.group(:name).count %>

<%#= line_chart @application.events.group_by_day(:created_at).count %>

<%= link_to "Edit", edit_registered_application_path, class: 'btn btn-success'  %>
<%= link_to "Delete", registered_application_path, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this application?'}  %>

app/views/user/index.html.erb
<h1>User#index</h1>


<% @users.each do |user| %>
<p><%= link_to user.name, user %></p>
<% end %>

app/views/user/show.html.erb
<h1>User#show</h1>
<p><%= @user.name %></p>

<p><%= link_to "New Application", new_registered_application_path %></p>

<% @user.registered_applications.each do |registered_application| %>
  <%= link_to registered_application do %>
    <p><%= registered_application.name %></p>
    <p><%= registered_application.url %></p>
    <p>User:<%= registered_application.user.id %></p>
    <br>
  <% end %>
<% end %>